name: Label New Issue

on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set labels based on issue title or body
      id: set_labels
      run: |
        declare -A label_map
        label_map=(
          ["feature"]="âœ¨ Feature"
          ["bug"]="ðŸž Bug"
          ["chore"]="âš™ Chore"
          ["documentation"]="ðŸ“ Docs"
          ["database"]="ðŸ—ƒ Database"
          ["emergency"]="ðŸš‘ Emergency"
          ["infrastructure"]="ðŸŒ Infrastructure"
          ["performance"]="âš¡ï¸ Performance"
          ["refactor"]="â™»ï¸ Refactor"
          ["remove"]="ðŸ”¥ Remove"
          ["security"]="ðŸ”’ Security"
          ["test"]="âœ… Test"
          ["warning"]="ðŸš¨ Warning"
        )

        label="ðŸª Later"  # Default label

        for keyword in "${!label_map[@]}"; do
          if [[ "${{ github.event.issue.title }}" == *"$keyword"* ]] || [[ "${{ github.event.issue.body }}" == *"$keyword"* ]]; then
            label="${label_map[$keyword]}"
            break
          fi
        done

        echo "LABELS=$label" >> $GITHUB_ENV

    - name: Add labels to issue
      uses: peter-evans/label-issues@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        labels: ${{ env.LABELS }}